config/routes.rb
Rails.application.routes.draw do
  get "users/index"
  get "users/statistics"
  get "/keyer/index"
  post '/users/export_to_pdf'
  post '/users/test_PDF'
  # config/routes.rb
  get "words/match_letters"
  get "home/index"
  get "/users/account"
  post "words/match_letters"

  patch "users/update_log"
  patch "users/update_log_words"

  devise_for :users

  resources :words
  
  root to: redirect('/keyer/index?level=auto')


  get "up" => "rails/health#show", as: :rails_health_check
  resources :letters do
    collection do
      get 'learn' 
      get 'keyer' 
      get 'free_learn' 
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
   
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def export_to_pdf
    statistics
    
    require 'base64'
    require 'stringio'
    image_data = params[:image_data]
    theImage = StringIO.new(Base64.decode64(image_data.split(',', 2).last))

    logs = @log
    formatted_logs = JSON.pretty_generate(@logs_json)
    learned = JSON.pretty_generate(@learned)
    inprocess = JSON.pretty_generate(@inprocess)
    newLen = JSON.pretty_generate(@new)
    views = JSON.pretty_generate(@views)
    average = JSON.pretty_generate(@average)
    predict = JSON.pretty_generate(@predict)

    export_date = Date.today.strftime("%Y-%m-%d")

    @pdf = Prawn::Document.new do
      pdf_height = 792
      font_families.update(
        'OpenSans' => {
          normal: Rails.root.join('app/assets/fonts/OpenSans-Regular.ttf'),
          bold: Rails.root.join('app/assets/fonts/OpenSans-Bold.ttf'), # Added comma here
          light: Rails.root.join('app/assets/fonts/OpenSans-Light.ttf')
        }
      )
      # stroke_horizontal_rule
  
      # header
      svg IO.read("app/assets/images/header.svg"), at: [-40 , bounds.height + 30], position: :center, width: 620
      text export_date, align: :right, size: 12, leading: 6, style: :ligh, color: "0000FF"
      move_down 10

      text "Overall progress", size: 20
      # text "Learned :"+ learned
      # text "Inprocess :"+inprocess
      # text "New :"+newLen
      # text "Views :"+views
      # text "Average :"+average
      # text "Predict :"+predict
      
      table_data = [
        [
          {content: "Learned:#{learned}\n\nInprocess:#{inprocess}\n\nNew:#{newLen}\n\nViews:#{views}\n\nAverage:#{average}\n\nPredict:#{predict}",
          size: 12,
          valign: :center,},
          {image: theImage,image_width: 450}
        ]
      ]

      # Utwórz tabelę i dostosuj jej styl
      table(table_data, position: :center, column_widths: [80, 450]) do
        cells.style(border_color: "FFFFFF")  # Ustawienie koloru obramowania na biały (FFFFFF)
      end
      move_down 10
   
      content = []
      text "History:", style: :bold, size: 22
      logs.reverse.each do |item|
        # content.push([" Date: #{item[:date]}"+" Yes: #{item[:yes]}"+" No: #{item[:no]}"+" Learned Letters: #{item[:learned_letters]}"]);
        text "Date: #{item[:date]}", style: :bold
        text "Yes: #{item[:yes]} No:#{item[:no]} Learned Letters: #{item[:learned_letters]}"
        stroke_horizontal_rule
        move_down 10
      end
      data = [ content.reverse ]
      move_down 20
    end

    pdf_data = Base64.encode64(@pdf.render)
    filename = "Statistics_#{@export_date}.pdf"
  
    render json: { pdf_data: pdf_data, filename: filename }
  
  end

  
  def test_PDF
    statistics
    image_data = params[:image_data]

    #PNG nie dziala
    # image_data_io = StringIO.new(Base64.decode64(image_data))
    # image_path = "app/assets/images/u8d12iks.png" 

    #działające PNG
    require 'base64'
    require 'stringio'
    theImage = StringIO.new(Base64.decode64(image_data.split(',', 2).last))
    puts image_data.split(',', 2).last

    #Próba zmiany PNG na JPG
    # require "mini_magick"
    # imageG = MiniMagick::Image.open(image_data_io)
    # imageG.format "png"

    #SVG
    # svg_data = params[:image_data]
    # puts svg_data

    @pdf = Prawn::Document.new do
      svg IO.read("app/assets/images/header.svg"), at: [-40 , bounds.height + 30], position: :center, width: 620

      #SVG
      # svg StringIO.new(svg_data), width: 500, color: :rgb, fill: '#f3f3f3'
      #czarnobiałe zdjęcie
      # image.write "output.png"
      #Nawet pobrany SVG nie działa 
      # svg IO.read("app/assets/images/c1x2z1ih.svg"), position: :center, width: 620

      #PNG
      # require 'base64'
      image theImage, width: 500
      # image image_data, width: 200
      #Prawn::Errors::UnsupportedImageType (image file is an unrecognised format)
      #PNG pobrany działa
      # image image_path, width: 200
    end
  
    pdf_data = Base64.encode64(@pdf.render)
    filename = "Statistics_.pdf"

    # send_data(@pdf.render,
    #   filename: "Statistics_#{@export_date}.pdf",
    #   type: 'application/pdf',
    #   disposition: 'inline')
  
    render json: { pdf_data: pdf_data, filename: filename }
  end

  # def statistics_pdf

  # end

  def index
    @users = User.all
  end
  def account
    statistics
  end
  def statistics
    @mode = params[:mode]
    @type = params[:type]
    learn_days = Log.where(user_id: current_user.id).length
    @yes = 0
    @no = 0
    if @mode == "week"
      @log = Log.where(user_id: current_user.id).last(7)
      if @log.length < 7
        dif = 6 - @log.length 
        for i in 0..dif
          @log.unshift(Log.new(user_id: current_user.id, date: (Date.today - (7-i)), yes: 0, no: 0,learned_letters: 0))
        end
      end
    else
      @log = Log.where(user_id: current_user.id).last(31)
      if @log.length < 31
        dif = 30 - @log.length 
        for i in 0..dif
          @log.unshift(Log.new(user_id: current_user.id, date: (Date.today - (30-i)), yes: 0, no: 0,learned_letters: 0))
        end
      end
    end
    @logs_json = @log.to_json
    learn = Learn.find_by(user_id: current_user.id)
    @learned = learn.learned.length
    @inprocess = learn.inprocess.length
    @new = learn.new.length
    @views = learn.data["views"]
    
    @log.each do |record|
      @yes += record.yes
      @no += record.no
    end

    if @learned != 0 
      @average = @learned.to_f / learn_days
      @predict = (34 - (@learned.to_f / @average)).ceil
    else
      @average = 0 
      @predict = 34
    end

  end

  def update_log_words

    if current_user
      puts "LEVEL"
      puts params[:data][0]

      learn = Learn.find_by(user_id: current_user.id)

      level = params[:data][0]
      if level == "a"
        level = learn.data["level"]
      else
        level = params[:data][0].to_i
      end
      

      
      learn.data["generated_pool"] = [];

      if params[:data][1..-1] == "yes"

        if learn.data["last_index_words"][level-1] == -1
          learn.data["last_index_words"][learn.data["level"]-1] = 1

          if learn.data["level_border"] > 10
            learn.data["level_border"] = learn.data["level_border"] - 4
          else  
            learn.data["level_border"] = 9
          end
          learn.data["level"]= learn.data["level"]+1

        end

      end

      learn.save
      head :ok
    else
      head :not_found
    end
  end  

  def update_log
    if current_user
      log = Log.find_by(user_id: current_user.id , date: Date.today)
      if log
        learn = Learn.find_by(user_id: current_user.id)
     
        generate_letter = learn.data["generated_pool"].shift(1)
        current_letters = learn.data["current_letters"]

        letter = current_letters.find { |item| item["letter"] == generate_letter[0]["letter"] }

        learn.data["views"] +=1
        letter["view_num"] = learn.data["views"]

        if params[:data][1..-1] == "yes"
          log.increment!(:yes)
          letter["level"] += 1
        elsif params[:data][1..-1] == "no"
          log.increment!(:no)
          if letter["level"] != 0
            letter["level"] -= 1
          end
        end
        # co ma się dziać jeśli ostatni tryb to remind albo nauka
        if learn.data["mode_history"][-1] == "remind"

          remind_letter = learn.learned.find { |item| item["letter"] == generate_letter[0]["letter"] }
          remind_letter["level"] = letter["level"]
          remind_letter["view_num"] = learn.data["views"]

          if params[:data][1..-1] == "no"
            learn.learned.delete_if { |item| item["letter"] == generate_letter[0]["letter"] }
            learn.data["current_letters"].delete_if { |item| item["letter"] == generate_letter[0]["letter"] }

            if remind_letter["level"] > 5
              learn.remind.push(letter)
            else
              learn.inprocess.push(letter)
            end

          end
        else

          inprocess_letter = learn.inprocess.find { |item| item["letter"] == generate_letter[0]["letter"] }
          if letter["level"] > 5
            log.increment!(:learned_letters)
            learn.learned.push(letter)
            learn.inprocess.delete_if { |item| item["letter"] == generate_letter[0]["letter"] }
            learn.data["generated_pool"].delete_if { |item| item["letter"] == generate_letter[0]["letter"] }
            learn.data["current_letters"].delete_if { |item| item["letter"] == generate_letter[0]["letter"] }
          end

          inprocess_letter["level"] = letter["level"]
          inprocess_letter["view_num"] = learn.data["views"]
  
        end

        learn.save
        head :ok
      else
        if params[:data][1..-1] == "yes"
          Log.create(user_id: current_user.id, date: Date.today, yes: 1, no: 0,learned_letters: 0)          
        elsif params[:data][1..-1] == "no"
          Log.create(user_id: current_user.id, date: Date.today, yes: 0, no: 1,learned_letters: 0)
        end
        head :ok
      end
    else
      head :not_found
    end
  end
  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.slim
.container.mt-4  
    = link_to "", keyer_index_path(level: "auto"), class: "back-link d-block"
    .h2.text-center style="font-size:2.3rem;margin-top:2.2em" Statistics
    br
    .fs-3.text-center.mt-4
        | Inprogress: #{@inprocess}
    .d-flex.gap-2.mx-auto.mt-2.justify-content-center
        .fs-3.text-center 
            | Learned: #{@learned}
    .chart.d-flex.justify-content-center
        #myChart1 data-stat="#{@logs_json}" data-type="#{@type}" data-mode="#{@week}" style="width:100%;height:16rem"
   
    hr
    = link_to "Log out", destroy_user_session_path, method: :delete, class: "text-center fs-2 mx-auto d-block mt-4"


/ - @log.each do |letter|
/     div
/         =< letter.id
/         =< letter.yes
/         =< letter.no
/         =< letter.learned_letters
/ canvas#myChart width="200" height="200" data-yes="#{@yes}" data-no="#{@no}"
script src="https://cdn.jsdelivr.net/npm/apexcharts" type="text/javascript"

= javascript_include_tag "account"

app/views/users/error.html.erb
<section class="page_404">
  <div class="container">
    <div class="row">  
      <div class="col-sm-12 ">
        <div class="col-sm-10 col-sm-offset-1  text-center">
          <div class="four_zero_four_bg">
            <h1 class="text-center "><%= @code %></h1>
          </div>
          
          <div class="contant_box_404">
            <h3 class="h2">
              Look like you're lost
            </h3>
            
            <p>the page you are looking for not available!</p>
            
            <%= link_to "home", home_index_path, class: "nav-link active" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.slim
h1.text-center All users
hr
.fs-5
  - @users.each do |user|
    div.mb-3
      = "#{user.email} #{user.email} #{user.role}"
      / = link_to "Edit", edit_user_path(user), class: "btn btn-primary mr-2"
      / = link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
    hr

app/views/users/statistics.html.slim
.container.mt-4  
    = link_to "", keyer_index_path(level: "auto"), class: "back-link"
    h2.text-center.h2-stat Statistics

    div.d-flex.justify-content-center.text-center.mb-1
        = link_to "Week", users_statistics_path(type: @type,mode: "week") , class: "link fs-6"+ (@mode == "week" ? " active-link" : "")
        = link_to "Month", users_statistics_path(type: @type,mode: "month") , class: "link fs-6"+ (@mode == "month" ? " active-link" : "")
    .d-flex.switch-type
        = link_to "Responses", users_statistics_path(type: "responses",mode: @mode) , class: "link fs-4 .p-2 "+ (@type == "responses" ? " active-type" : "")
        = link_to "Progress", users_statistics_path(type: "progress",mode: @mode) , class: "link fs-4 .p-2 "+ (@type == "progress" ? " active-type" : "")

    .chart.d-flex.justify-content-center
        #myChart1 data-stat="#{@logs_json}" data-type="#{@type}" data-mode="#{@mode}" style="width:60%"
        #myChart2 data-inporgress="#{@inprocess}" data-new="#{@new}" data-learned="#{@learned}" data-no="#{@no}"  data-yes="#{@yes}" style="margin-top:2em"
    = link_to "Export as PDF", users_export_to_pdf_path , class:"btn btn-dark text-light px-10 d-block export_to_pdf", style:"margin-right:6rem;margin-left:auto;width:9rem"
    .d-flex.justify-content-center.prediction
        .fs-3.mx-auto.mt-3.d-flex.justify-content-baseline.align-items-baseline.position-relative
            .header Prediction
            .d-flex style="gap:5px;"
                span To learn all letters, you need 
                strong #{@predict}days more 
                span if you'll practice
                u every day
            i.fs-5.position-absolute.end-0  style="bottom:-2rem"
                Prediction Based on your statistics*    
/ div.justify-content-space-bettwen.d-flex
/     div.d-flex.gap-2.justify-content-center style="width:50%"
/         p.fs-3 
/             | No: #{@no}
/         p.fs-3 
/             | Yes: #{@yes}
/     div.d-flex.gap-2.justify-content-center style="width:50%"
/         p.fs-3 
/             | Inprogress: #{@inprocess}
/         p.fs-3 
/             | Learned: #{@learned}
/         p.fs-3 
/             | New: #{@new}



/ - @log.each do |letter|
/     div
/         =< letter.id
/         =< letter.yes
/         =< letter.no
/         =< letter.learned_letters
/ canvas#myChart width="200" height="200" data-yes="#{@yes}" data-no="#{@no}"
script src="https://cdn.jsdelivr.net/npm/apexcharts" type="text/javascript"

= javascript_include_tag "statistics"