config/routes.rb
Rails.application.routes.draw do
  get "users/index"
  get "users/statistics"
  get "/keyer/index"
  post '/users/export_to_pdf'
  post '/users/test_PDF'
  # config/routes.rb
  get "words/match_letters"
  get "home/index"
  get "/users/account"
  post "words/match_letters"

  patch "users/update_log"
  patch "users/update_log_words"

  devise_for :users

  resources :words
  
  root to: redirect('/keyer/index?level=auto')


  get "up" => "rails/health#show", as: :rails_health_check
  resources :letters do
    collection do
      get 'learn' 
      get 'keyer' 
      get 'free_learn' 
    end
  end
  
end

app/models/letter.rb
class Letter < ApplicationRecord
	validates :letter, presence: true, length:{maximum:1}
	validates :morse_code, presence: true ,format: { with: /\A[.-]+\z/, message: "Can only contain '-' and '.'" }
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: %i[ show edit update destroy ]

  # GET /letters or /letters.json
  def index
    @letters = Letter.all
    learn  = Learn.find_by(user_id: current_user.id)
    @un_lock= [*learn.learned].to_json
    puts "ooooooooooo"
    puts learn.learned
  end

  # GET /letters/1 or /letters/1.json
  def show
  end

  def keyer
    @letters = Letter.all.select(:letter, :morse_code).to_json
    learn
  end

  def learn
    learn  = Learn.find_by(user_id: current_user.id)
    current_pool = learn.data["generated_pool"]
    history =  learn.data["mode_history"]
    @letter

    # sprawdza dwa ostatnio wywołane tryby to nauka czy przypomnienie liter
    if current_pool.blank?
      if learn.data["mode_history"][-2..-1].all? { |el| el == "learn" } && learn.new.length > 0
        learn.data["mode_history"].push("remind")
        current_pool = create_remind_pool
      else
      learn.data["mode_history"].push("learn")
      current_pool = create_learn_pool
      learn.data["mode_history"] = learn.data["mode_history"].last(3)
      end
      learn.data["generated_pool"] = current_pool[0]
      learn.data["current_letters"] = current_pool[1]
      @letter = current_pool[0][0]
    else
    @letter = current_pool[0]
    end
    # @level = learn.data["current_letters"].find { |letter| letter["letter"] == @letter["letter"] }&.fetch("level", nil)
    learn.save
    #@current = learn.data["current_letters"].find { |item| item["letter"] == @letter["letter"] }
    @cur = learn.data["current_letters"]
    @learned = learn.learned
    @gen = learn.data["generated_pool"]
    @gen_letter_json = learn.data["generated_pool"].to_json
    @hist = learn.data["mode_history"]

    # if @current["level"] < 3
    #   @mode = "text"
    #   @reverse = false
    # else
    @mode = "text"
    @reverse = "false"
    # end 

  end

  def create_remind_pool
    learn = Learn.find_by(user_id: current_user.id)
    learned = learn.learned
    pool = []
    learned.sort_by! { |obj| obj["view_num"] }

    if learned.length > 6
      pool.push(learned[0..5])
    else
      pool = learned
    end
    learn.save

    return [pool,pool]
  end

  def create_learn_pool
    learn = Learn.find_by(user_id: current_user.id)
    inprocess = learn["inprocess"]
    pool = []

    if inprocess.length < 3
      how_many_add = -(inprocess.length) + 5
      newLetters = learn.new.shift(how_many_add)
      pool.push(*newLetters)
      learn.inprocess.push(*newLetters)
    else
      pool = inprocess
    end

    learn.save
    p = inprocess
    p = p.sort_by! { |obj| obj["level"] }
    tab = []
    tab.push(p[0],p[0],p[0],p[1],p[1],p[1],p[2],p[2],p[2],p[2]).shuffle!
    return [tab,pool]
  end

  def free_learn
    @letter = Letter.order("RANDOM()").first
    @mode = params[:mode]
    @reverse = params[:reverse]
  
    Rails.logger.debug("Received mode: #{@mode}")
    Rails.logger.debug("Received reverse: #{@reverse}")
  end

  # GET /letters/new
  def new
    @letter = Letter.new
  end

  # GET /letters/1/edit
  def edit
  end

  # POST /letters or /letters.json
  def create
    @letter = Letter.new(letter_params)

    respond_to do |format|
      if @letter.save
        format.html { redirect_to letter_url(@letter), notice: "Letter was successfully created." }
        format.json { render :show, status: :created, location: @letter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letters/1 or /letters/1.json
  def update
    respond_to do |format|
      if @letter.update(letter_params)
        format.html { redirect_to letter_url(@letter), notice: "Letter was successfully updated." }
        format.json { render :show, status: :ok, location: @letter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1 or /letters/1.json
  def destroy
    @letter.destroy!

    respond_to do |format|
      format.html { redirect_to letters_url, notice: "Letter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def letter_params
      params.require(:letter).permit(:letter, :morse_code)
    end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/_form.html.slim
= form_with(model: letter) do |form|
  - if letter.errors.any?
    div style="color: red"
      h2 = "#{pluralize(letter.errors.count, "error")} prohibited this letter from being saved:"
      ul
        - letter.errors.each do |error|
          li = error.full_message

  div
    = form.label :letter, style: "display: block"
    = form.text_field :letter

  div
    = form.label :morse_code, style: "display: block"
    = form.text_field :morse_code

  div
    = form.submit

app/views/letters/_letter.html.slim
.letter-box.mx-auto
  p =< letter.letter

    

    

app/views/letters/edit.html.slim
h1 Editing letter

== render "form", letter: @letter

br

div
  => link_to "Show this letter", @letter
  '|
  =< link_to "Back to letters", letters_path

app/views/letters/free_learn.html.slim
h1.text-center.mt-2.mb-4 Learn

.div.mt-1 style="position: relative"
    .card.fs-1.d-flex.justify-content-center.align-items-center.learn-card class=(@reverse == "false" ? "" : "flip")
        .letter
            = @letter.letter
        .morse-code(data-mode="#{@mode}" data-reverse="#{@reverse}" data-code="#{@letter.morse_code}" data-letter="#{@letter.letter}")
            .light style=(@mode=="light" ? "" : "display:none")
                .bulb
            .speaker style=(@mode=="sound" ? "" : "display:none")   
            = @letter.morse_code if @reverse=="true" && @mode == "text"
        .controls 
            button.btn#no
                .img 
            button.btn#yes
                .img 
            button.btn#flip.fs-4.btn-primary.mx-auto
                |Flip card
    
.bottom-panel.d-flex.select-laarn-type.mx-auto.fs-5.mt-3
    .d-flex.fs-5.align-items-center.gap-1.align-items-baseline
        |First display: #{@reverse == "false" ? " letter " : " code "}
        =link_to "", free_learn_letters_path(mode: @mode , reverse: (@reverse == "false" ? true : false)), class: "link switch-rev"
    div.d-flex 
        |Learn mode:
        = link_to "Text", free_learn_letters_path(mode: "text", reverse: @reverse) , class: "link fs-6"+ (@mode == "text" ? " active-link" : "")
        = link_to "Light", free_learn_letters_path(mode: "light", reverse: @reverse) , class: "link fs-6"+ (@mode == "light" ? " active-link" : "")
        = link_to "Sound", free_learn_letters_path(mode: "sound", reverse: @reverse) , class: "link fs-6"+ (@mode == "sound" ? " active-link" : "")

= javascript_include_tag "free_learn"

app/views/letters/free_learn.js.erb
document.querySelector('.learn-card .letter').innerHTML = '<%= @letter.letter %>';
document.querySelector(".learn-card .morse-code").dataset.code = '<%= @letter.morse_code %>';
document.querySelector(".learn-card .morse-code").dataset.letter = '<%= @letter.letter %>';
document.querySelector(".learn-card").classList.remove("flip");

app/views/letters/index.html.slim
.container.game-container
  p style="color: green" = notice

  = render 'layouts/banner' 

  .command.text-center.mt-sm-4.mt-5
    | Your letters


  .letters-box data-un-lock="#{@un_lock}"
    - @letters.each do |letter|
      == render letter

  = render 'layouts/bottom_menu'  
.panel.d-none.d-sm-block
  = render 'layouts/bottom_desktop_menu' 

= javascript_include_tag "letters"

app/views/letters/keyer.html.slim
/ h1.text-center.mt-2.mb-4 Learn
/ = @current
/ h4 Odstatnie tryby 
/ = @hist
/ h4 Wygenerowane
/ div.d-flex.fs-3
/     - @gen.each do |letter|
/         div 
/             =< ". #{letter["letter"]} L:#{letter["level"]} V:#{letter["view_num"]} "
/ h4 Obecne litery
/ div.fs-3
/     - @cur.each do |letter|
/         div 
/             =< "- #{letter["letter"]} L:#{letter["level"]} V:#{letter["view_num"]} "
/ h4 Nauczone
/ div.d-flex.fs-3
/     - @learned.each do |letter|
/         div 
/             =< ". #{letter["letter"]} L:#{letter["level"]} V:#{letter["view_num"]} "
/ h1.text-center.d-flex.mx-auto.justify-content-center style="margin-top:40px;color:#0d6efd"
/     .letters
/     .blur ?
div.position-relative.d-block style="height:150px;margin-bottom:3rem"
    span.position-absolute.top-50.start-50.translate-middle.bg-black.z-3 style="height:150px;width:2px;"
    canvas.mx-auto.d-block.border-5.mt-3.position-absolute.top-50.start-50.translate-middle.z-2 id="myCanvas" width="1000px" height="120px" data-letters="#{@letters}" data-generatedPool="#{@gen_letter_json}"
    canvas.mx-auto.d-block.border-5.mt-3.position-absolute.top-50.start-50.translate-middle.z-4 id="tutor" width="1000px" height="120px" data-letters="#{@letters}" 
button.button-67 Play
button.fs-4.btn-black.mx-auto.text-center Reset 
.container style="color:white"
    #sygnalTime
    #signals
    #codes  
    
= javascript_include_tag "learn_keyer"

app/views/letters/learn.html.slim
h1.text-center.mt-2.mb-4 Learn
= @current
h4 Odstatnie tryby 
= @hist
h4 Wygenerowane
div.d-flex.fs-3
    - @gen.each do |letter|
        div 
            =< ". #{letter["letter"]} L:#{letter["level"]} V:#{letter["view_num"]} "
h4 Obecne litery
div.fs-3
    - @cur.each do |letter|
        div 
            =< "- #{letter["letter"]} L:#{letter["level"]} V:#{letter["view_num"]} "
h4 Nauczone
div.d-flex.fs-3
    - @learned.each do |letter|
        div 
            =< ". #{letter["letter"]} L:#{letter["level"]} V:#{letter["view_num"]} "

.div.mt-1 style="position: relative"
    .card.fs-1.d-flex.justify-content-center.align-items-center.learn-card class=(@reverse == "false" ? "" : "flip")
        .letter
            = @letter["letter"]
        .morse-code(data-mode="#{@mode}" data-reverse="#{@reverse}" data-code="#{@letter["morse_code"]}" data-letter="#{@letter["letter"]}")
            .light style=(@mode=="light" ? "" : "display:none")
                .bulb
            .speaker style=(@mode=="sound" ? "" : "display:none")   
            = @letter["morse_code"] if @reverse=="true" && @mode == "text"
        .controls 
            button.btn#no
                .img 
            button.btn#yes
                .img 
            button.btn#flip.fs-4.btn-primary.mx-auto
                |Flip card
= javascript_include_tag "learn"

app/views/letters/learn.js.erb
document.querySelector('.learn-card .letter').innerHTML = '<%= j @letter["letter"] %>';
document.querySelector(".learn-card .morse-code").dataset.code = '<%= j @letter["morse_code"] %>';
document.querySelector(".learn-card .morse-code").dataset.letter = '<%= j @letter["letter"] %>';
document.querySelector(".learn-card").classList.remove("flip");

app/views/letters/new.html.slim
h1 New letter

== render "form", letter: @letter

br

div
  = link_to "Back to letters", letters_path

app/views/letters/show.html.slim
p style="color: green" = notice

== render @letter


div
  => link_to "Edit this letter", edit_letter_path(@letter)
  '|
  =< link_to "Back to letters", letters_path

  = button_to "Destroy this letter", @letter, method: :delete