config/routes.rb
Rails.application.routes.draw do
  get "users/index"
  get "users/statistics"
  get "/keyer/index"
  post '/users/export_to_pdf'
  post '/users/test_PDF'
  # config/routes.rb
  get "words/match_letters"
  get "home/index"
  get "/users/account"
  post "words/match_letters"

  patch "users/update_log"
  patch "users/update_log_words"

  devise_for :users

  resources :words
  
  root to: redirect('/keyer/index?level=auto')


  get "up" => "rails/health#show", as: :rails_health_check
  resources :letters do
    collection do
      get 'learn' 
      get 'keyer' 
      get 'free_learn' 
    end
  end
  
end

app/models/word.rb
class Word < ApplicationRecord
    before_save :generate_output_text

    def generate_output_text
      self.morse_code = translate_to_morse(self.word)
      self.view_num = 0
    end

    def translate_to_morse(text)
        translation = ''
    
        text.downcase.each_char do |char|
          letter = Letter.find_by(letter: char)
          translation << (letter.morse_code + ' ')
        end
    
        self.morse_code = translation.strip
      end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: %i[ show edit update destroy ]

  # GET /words or /words.json
  def index
    @words = Word.all
  end

  def match_letters
    word = Word.all.sample 
    @letters = word.word.split("")
    @codes = word.morse_code.split(" ")
    @mixCodes = [*@codes]
    counter = 0
    
    begin
      letter = Letter.all.sample
      if Letter.all.include?(letter)
        @mixCodes.push(letter.morse_code)
        counter += 1
      end
    end while counter < 2
    @mixCodes = @mixCodes.shuffle

  end

  def match_letters_update
    word = Word.all.sample 
    @letters = word.word.split("")
    @codes = word.morse_code.split(" ")
    @mixCodes = [*@codes]
    counter = 0
    
    begin
      letter = Letter.all.sample
      if Letter.all.include?(letter)
        @mixCodes.push(letter.morse_code)
        counter += 1
      end
    end while counter < 2
    @mixCodes = @mixCodes.shuffle

    respond_to do |format|
      format.turbo_stream
      headers['Turbo-Frame'] = 'match_letters_frame'
      format.turbo_stream { render turbo_stream: turbo_stream.replace('match_letters_frame', partial: 'words/new_letters') }
    end
  end

  # GET /words/1 or /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words or /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to word_url(@word), notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1 or /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to word_url(@word), notice: "Word was successfully updated." }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1 or /words/1.json
  def destroy
    @word.destroy!

    respond_to do |format|
      format.html { redirect_to words_url, notice: "Word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:word, :morse_code)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.slim
= simple_form_for(@word) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :word
    = f.input :morse_code

  .form-actions
    = f.button :submit

app/views/words/_new_letters.html.slim
.card.fs-1.d-flex.justify-content-between.learn-card.pt-5.pb-4 style="max-width: 60rem"
    .mt-3
        .d-flex.gap-3.letters.justify-content-center.fs-3  data-letters="#{@letters}"
            - @letters.each do |el|
                .p-2.text-center style="height:7rem"
                    .answear-box style="min-height:3.6rem;min-width:4rem; box-shadow: inset 0 0 10px #dedede"
                    span = el
        .d-flex.gap-3.codes.justify-content-center.mt-2.fs-3
            - @mixCodes.each do |el|
                .border-bottom.p-2.border-2.border-dark.code.text-center style="min-width:3rem" draggable="true"
                    =el

    button#check-answear.btn.btn-primary.mx-auto.fs-4.d-block.mt-5.px-4 data-answear="#{@codes}" 
        | Check answear

app/views/words/_word.html.slim
div.list-group-item.fs-5 id="#{dom_id word}"
  p
    strong Word:
    =< word.word
  p
    strong Morse code:
    =< word.morse_code
  p
    strong level / views:
    =< word.level 
    | /
    =< word.view_num 

app/views/words/edit.html.slim
h1 Editing word

== render "form", word: @word

br

div
  => link_to "Show this word", @word
  '|
  =< link_to "Back to words", words_path

app/views/words/index.html.slim
= render 'layouts/navbar' 
p style="color: green" = notice

h1 Words

#words.list-group
  - @words.each do |word|
    == render word
    / p
    /   = link_to "Show this word", word

= link_to "New word", new_word_path

app/views/words/match_letters.html.slim
h1.text-center.mt-2.mb-4
    | Letter match


= render 'new_letters'

/ = button_to 'Reload',words_match_letters_path, remote: true, method: :post 

/ button#reload.btn.btn-primary.mx-auto
/     | Reload

/ = @mixCodes 
.fs-3.text-center
    = @codes
.fs-3.text-center
    = @letters


= javascript_include_tag "match_letters"

app/views/words/new.html.slim
h1 New word

== render "form", word: @word

br

div
  = link_to "Back to words", words_path

app/views/words/show.html.slim
p style="color: green" = notice

== render @word

div
  => link_to "Edit this word", edit_word_path(@word)
  '|
  =< link_to "Back to words", words_path

  = button_to "Destroy this word", @word, method: :delete