config/routes.rb
Rails.application.routes.draw do
  get "users/index"
  get "users/statistics"
  get "/keyer/index"
  post '/users/export_to_pdf'
  post '/users/test_PDF'
  # config/routes.rb
  get "words/match_letters"
  get "home/index"
  get "/users/account"
  post "words/match_letters"

  patch "users/update_log"
  patch "users/update_log_words"

  devise_for :users

  resources :words
  
  root to: redirect('/keyer/index?level=auto')


  get "up" => "rails/health#show", as: :rails_health_check
  resources :letters do
    collection do
      get 'learn' 
      get 'keyer' 
      get 'free_learn' 
    end
  end
  
end

app/views/layouts/_banner.html.slim
.mx-3.mt-3.d-sm-none
    .row.my-4.px-1
        .col-10.d-flex
            .logo 
            .fs-2 LEARN MORSE
        .col-2.speaker-on

app/views/layouts/_bottom_desktop_menu.html.slim
.d-md-flex.d-none.desktop-bottom-menu.justify-contetn-end
    = link_to "Learn", keyer_index_path(level: "auto"), class: "text-center"
    = link_to "Your letters", letters_path , class: "text-center"
    = link_to "Statistics", users_statistics_path(type: "responses",mode: "week"), class: "text-center"
    = link_to "Log out", destroy_user_session_path, method: :delete, class: "text-center"

app/views/layouts/_bottom_menu.html.slim
.bottom-menu.d-sm-none
    .box
        .icon.learn-icon
            = link_to "Learn", keyer_index_path(level: "auto"), class: "text-white"
    .box
        .icon.letter-icon 
            = link_to "Your letters", letters_path , class: "text-white"
    .box
        .icon.account-icon
             = link_to "Account", users_account_path(mode: "week", type: "responses"), class: "text-white"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.me-auto
  .container-fluid
    .fs-2.navbar-brand.main-color 
      |LEARN MORSE
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    .collapse.navbar-collapse id="navbarTogglerDemo02"
      ul.navbar-nav.ms-auto.mb-2.mb-lg-0.fs-4
        li.nav-item
          = link_to "Letters", letters_path , class: "nav-link active"
        li.nav-item
          = link_to "Words", words_path , class: "nav-link active"
        li.nav-item
          = link_to "Free learn", free_learn_letters_path(mode: "text",reverse: "false") , class: "nav-link active"
        li.nav-item
          = link_to "Letter match", words_match_letters_path , class: "nav-link active"
        - if user_signed_in?
          - if can? :menage, @user
            li.nav-item
              = link_to "Users", users_index_path, class: "nav-link active"
          li.nav-item
            = link_to "Statistics", users_statistics_path(type: "responses",mode: "week"), class: "nav-link active"
          li.nav-item
            = link_to "Learn", keyer_index_path(level: "auto") , class: "nav-link active"
          li.nav-item
            = link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link active"
        - else
          li.nav-item
            = link_to "Sign up", new_user_registration_path(mode: "text"), class: "nav-link active"
          li.nav-item
            = link_to "Sign in", new_user_session_path, class: "nav-link active"

hr.border.border-black.border-1.opacity-50.mt-0

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Morse</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "light", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@1,500&family=Noto+Serif:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Prompt:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300;1,400;1,500&family=Raleway:ital,wght@0,300;1,200&display=swap" rel="stylesheet">
    <%# <%= turbo_include_tags %> 

  </head>
    <%= javascript_include_tag "application" %>
  <body>
    <%= yield %>
  </body>
</html>